---
- name: sovbox
  hosts: sovbox
  become: yes

  roles:
    - sovbox
    - { name: groestlcoind, tags: ['groestlcoind'] }
    - { name: electrumx, tags: ['electrumx'] }
    - { name: grs-rpc-explorer, tags: ['grs-rpc-explorer'] }
