---
- name: nodejs
  include_role: name=nodejs

# apt packages: python3-software-properties  software-properties-common nginx

- name: npm install pm2
  npm:
    name: pm2
    global: yes
  tags:
    - grsrpcxpl-install


# Ran into this issue https://github.com/janoside/btc-rpc-explorer/issues/137
#- name: npm install grs-rpc-explorer
#  command: npm install -g grs-rpc-explorer
#  tags:
#   - grsrpcxpl-install


# add-apt-repository ppa:certbot/certbot
# apt update
# apt upgrade
# apt install python-certbot-nginx
# Copy content from ./grs-explorer.com.conf into /etc/nginx/sites-available/grs-explorer.com.conf

# certbot --nginx -d grs-explorer.com
# cd /etc/ssl/certs
# openssl dhparam -out dhparam.pem 4096
# cd /home/groestlcoin
# git clone https://github.com/Groestlcoin/grs-rpc-explorer.git
# cd /home/groestlcoin/grs-rpc-explorer
# npm install
# npm run build
# pm2 start bin/www --name "grs-rpc-explorer"
